language: generic
os:
  - linux

dist: xenial

addons:
  apt:
    packages:
    - python-qt4
    - python-pip
    - python-numpy
    - python-scipy
    - python-pyqtgraph
    - python-matplotlib
    - python-taurus
    - python-psutil
    - python-tk
    - python-sardana
    - python-coverage
    - xvfb

install: 
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - sudo dpkg -i /home/travis/build/thorstenkracht/PySpectra/HasyUtils/python-hasyutils_1.55555_amd64.deb

script:
  - cd /home/travis/build/thorstenkracht/PySpectra
  - echo $PWD
  - echo $DISPLAY
  - python2-coverage run -m unittest discover -v
