language: generic
os:
  - linux

dist: xenial

addons:
  apt:
    packages:
    - python-qt4
    - python-pip

#install: 
#  - pip install --user pytest
script:
  - cd /home/travis/build/thorstenkracht/PySpectra
  - echo $PWD
  - python -m unittest discover -v
